homeassistant:
  name: Hidden Ridge Alarm
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 360
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include_dir_merge_named customize

frontend:
updater:
recorder:
history:
logbook:
http: !include ./configuration/http.yaml
binary_sensor: !include ./configuration/binary_sensor.yaml
mqtt:
  broker: 10.0.0.212
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true

group:
  zones:
    - binary_sensor.front_door
    - binary_sensor.garage_door
    - binary_sensor.front_windows
    - binary_sensor.back_door
    - binary_sensor.back_windows
    - binary_sensor.bedroom_windows
  mqtt:
    - binary_sensor.front_door__mqtt
    - binary_sensor.garage_door__mqtt
    - binary_sensor.front_windows__mqtt
    - binary_sensor.back_door__mqtt
    - binary_sensor.back_windows__mqtt
    - binary_sensor.bedroom_windows__mqtt
