- platform: rpi_gpio
  ports:
    4: Front Door
    18: Garage Door
    17: Back Door
    27: Front Windows
    22: Bedroom Windows
    6: Back Windows
- platform: mqtt
  name: "Front Door"
  sensor_class: opening
  state_topic: "/rpi-alarm/out/7"
  payload_on: "1"
  payload_off: "0"
